# File: .github/workflows/conda-release.yml

name: Release Metax to Bioconda

on:
  # Manual trigger (for testing)
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 0.9.0)'
        required: true
  # Trigger on published GitHub Releases
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install micromamba and create a build environment
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: buildenv
          channels: conda-forge,bioconda
          channel-priority: strict
          create-args: |
            python=3.10
            conda-build
            anaconda-client

      # 3. Determine the version to build
      - name: Determine version
        id: version
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.version }}"
          else
            TAG="${GITHUB_REF_NAME#v}"
          fi
          echo "VERSION=${TAG}" >> $GITHUB_ENV

      # 4. Download the release tarball
      - name: Download metax.tar.gz
        run: wget -O metax.tar.gz \
            "https://github.com/dawnmy/Metax/releases/download/v${VERSION}/metax.tar.gz"
        env:
          VERSION: ${{ env.VERSION }}

      # 5. Compute its SHA-256 checksum
      - name: Compute SHA-256 checksum
        id: checksum
        run: echo "SHA256=$(sha256sum metax.tar.gz | cut -d ' ' -f1)" >> $GITHUB_ENV

      # 6. Update recipe/meta.yaml (version, url, sha256)
      - name: Update recipe/meta.yaml
        run: |
          sed -i -E "s|^[[:space:]]*version:.*|  version: \"${VERSION}\"|" recipe/meta.yaml
          sed -i -E "s|^[[:space:]]*url:.*|  url: https://github.com/dawnmy/Metax/releases/download/v${VERSION}/metax.tar.gz|" recipe/meta.yaml
          sed -i -E "s|^[[:space:]]*sha256:.*|  sha256: ${SHA256}|" recipe/meta.yaml
        env:
          VERSION: ${{ env.VERSION }}
          SHA256: ${{ env.SHA256 }}

      # 7. Build the Conda package (skip tests)
      - name: Build Conda package
        run: micromamba run -n buildenv conda-build recipe/ --no-test

      # 8. Upload the built package to bioconda
      - name: Upload to Bioconda
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          # Authenticate non-interactively
          micromamba run -n buildenv anaconda auth login --token "$ANACONDA_TOKEN"
          # Find the built package path
          PKG=$(micromamba run -n buildenv conda-build --output recipe/)
          # Upload it
          micromamba run -n buildenv anaconda upload --force --user bioconda "$PKG"