# File: .github/workflows/conda-release.yml

name: Release Metax to Bioconda

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 0.9.0)'
        required: true
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          auto-activate-base: false

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.version }}"
          else
            TAG="${GITHUB_REF_NAME#v}"
          fi
          echo "VERSION=${TAG}" >> $GITHUB_ENV
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Download release tarball
        run: wget -O metax.tar.gz "https://github.com/dawnmy/Metax/releases/download/v${VERSION}/metax.tar.gz"
        env:
          VERSION: ${{ env.VERSION }}

      - name: Compute SHA-256 checksum
        id: checksum
        run: |
          echo "SHA256=$(sha256sum metax.tar.gz | cut -d ' ' -f1)" >> $GITHUB_ENV

      - name: Update recipe/meta.yaml
        run: |
          sed -i -E "s|^[[:space:]]*version:.*|  version: \"${VERSION}\"|" recipe/meta.yaml
          sed -i -E "s|^[[:space:]]*url:.*|  url: https://github.com/dawnmy/Metax/releases/download/v${VERSION}/metax.tar.gz|" recipe/meta.yaml
          sed -i -E "s|^[[:space:]]*sha256:.*|  sha256: ${SHA256}|" recipe/meta.yaml
        env:
          VERSION: ${{ env.VERSION }}
          SHA256: ${{ env.CHECKSUM }}

      - name: Configure Conda channels
        run: |
          conda config --add channels conda-forge
          conda config --add channels bioconda
          conda config --set channel_priority strict

      - name: Install build tools
        run: |
          conda install --yes conda-build
          pip install anaconda-client

      - name: Build Conda package
        run: conda build recipe/

      - name: Upload to Bioconda
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          anaconda auth login --token "$ANACONDA_TOKEN"
          PKG=$(conda build recipe/ --output)
          anaconda upload --force --user bioconda "$PKG"